from __future__ import annotations

from typing import Final


COUNTRY_NAME_MAP: Final[dict[str, str]] = {
    "china mainland": "中国",
    "china": "中国",
    "中国": "中国",
    "people's republic of china": "中国",
    "hong kong": "中国香港特别行政区",
    "hk": "中国香港特别行政区",
    "中国香港特别行政区": "中国香港特别行政区",
    "香港": "中国香港特别行政区",
    "taiwan": "中国台湾省",
    "tw": "中国台湾省",
    "台湾": "中国台湾省",
    "中国台湾省": "中国台湾省",
    "macao": "中国澳门特别行政区",
    "macau": "中国澳门特别行政区",
    "澳门": "中国澳门特别行政区",
    "中国澳门特别行政区": "中国澳门特别行政区",
    "united states": "美国",
    "usa": "美国",
    "美国": "美国",
    "singapore": "新加坡",
    "新加坡": "新加坡",
    "germany": "德国",
    "德国": "德国",
    "japan": "日本",
    "日本": "日本",
    "finland": "芬兰",
    "芬兰": "芬兰",
    "france": "法国",
    "法国": "法国",
    "united kingdom": "英国",
    "uk": "英国",
    "great britain": "英国",
    "britain": "英国",
    "英国": "英国",
    "netherlands": "荷兰",
    "荷兰": "荷兰",
    "india": "印度",
    "印度": "印度",
    "australia": "澳大利亚",
    "澳大利亚": "澳大利亚",
    "canada": "加拿大",
    "加拿大": "加拿大",
    "south korea": "韩国",
    "republic of korea": "韩国",
    "korea, republic of": "韩国",
    "韩国": "韩国",
    "malaysia": "马来西亚",
    "马来西亚": "马来西亚",
    "russia": "俄罗斯",
    "russian federation": "俄罗斯",
    "俄罗斯": "俄罗斯",
    "brazil": "巴西",
    "巴西": "巴西",
    "vietnam": "越南",
    "越南": "越南",
    "indonesia": "印度尼西亚",
    "印尼": "印度尼西亚",
    "印度尼西亚": "印度尼西亚",
    "thailand": "泰国",
    "泰国": "泰国",
    "united arab emirates": "阿联酋",
    "uae": "阿联酋",
    "阿联酋": "阿联酋",
    "ireland": "爱尔兰",
    "爱尔兰": "爱尔兰",
    "sweden": "瑞典",
    "瑞典": "瑞典",
    "south africa": "南非",
    "南非": "南非",
    "spain": "西班牙",
    "西班牙": "西班牙",
    "italy": "意大利",
    "意大利": "意大利",
    "switzerland": "瑞士",
    "瑞士": "瑞士",
    "philippines": "菲律宾",
    "菲律宾": "菲律宾",
    "mexico": "墨西哥",
    "墨西哥": "墨西哥",
    "turkey": "土耳其",
    "土耳其": "土耳其",
    "saudi arabia": "沙特阿拉伯",
    "沙特阿拉伯": "沙特阿拉伯",
    "new zealand": "新西兰",
    "新西兰": "新西兰",
    "belgium": "比利时",
    "比利时": "比利时",
    "norway": "挪威",
    "挪威": "挪威",
    "denmark": "丹麦",
    "丹麦": "丹麦",
    "poland": "波兰",
    "波兰": "波兰",
    "ukraine": "乌克兰",
    "乌克兰": "乌克兰",
    "iran": "伊朗",
    "iran, islamic republic of": "伊朗",
    "伊朗": "伊朗",
    "pakistan": "巴基斯坦",
    "巴基斯坦": "巴基斯坦",
    "czech republic": "捷克",
    "czechia": "捷克",
    "捷克": "捷克",
    "austria": "奥地利",
    "奥地利": "奥地利",
    "romania": "罗马尼亚",
    "罗马尼亚": "罗马尼亚",
    "israel": "以色列",
    "以色列": "以色列",
    "argentina": "阿根廷",
    "阿根廷": "阿根廷",
    "chile": "智利",
    "智利": "智利",
    "slovenia": "斯洛文尼亚",
    "斯洛文尼亚": "斯洛文尼亚",
    "türkiye": "土耳其",
    "turkiye": "土耳其",
    "latvia": "拉脱维亚",
    "拉脱维亚": "拉脱维亚",
    "lithuania": "立陶宛",
    "立陶宛": "立陶宛",
    "kazakhstan": "哈萨克斯坦",
    "哈萨克斯坦": "哈萨克斯坦",
    "morocco": "摩洛哥",
    "摩洛哥": "摩洛哥",
    "european union": "欧盟",
    "欧盟": "欧盟",
    "bulgaria": "保加利亚",
    "保加利亚": "保加利亚",
    "hungary": "匈牙利",
    "匈牙利": "匈牙利",
    "slovakia": "斯洛伐克",
    "斯洛伐克": "斯洛伐克",
    "portugal": "葡萄牙",
    "葡萄牙": "葡萄牙",
    "estonia": "爱沙尼亚",
    "爱沙尼亚": "爱沙尼亚",
    "bangladesh": "孟加拉国",
    "孟加拉国": "孟加拉国",
    "colombia": "哥伦比亚",
    "哥伦比亚": "哥伦比亚",
    "moldova": "摩尔多瓦",
    "摩尔多瓦": "摩尔多瓦",
    "myanmar (burma)": "缅甸",
    "myanmar": "缅甸",
    "缅甸": "缅甸",
    "bahrain": "巴林",
    "巴林": "巴林",
    "egypt": "埃及",
    "埃及": "埃及",
    "armenia": "亚美尼亚",
    "亚美尼亚": "亚美尼亚",
    "mauritius": "毛里求斯",
    "毛里求斯": "毛里求斯",
    "nepal": "尼泊尔",
    "尼泊尔": "尼泊尔",
    "bahamas": "巴哈马",
    "巴哈马": "巴哈马",
    "georgia": "格鲁吉亚",
    "格鲁吉亚": "格鲁吉亚",
    "albania": "阿尔巴尼亚",
    "阿尔巴尼亚": "阿尔巴尼亚",
    "peru": "秘鲁",
    "秘鲁": "秘鲁",
    "mongolia": "蒙古",
    "蒙古": "蒙古",
    "greece": "希腊",
    "希腊": "希腊",
    "burkina faso": "布基纳法索",
    "布基纳法索": "布基纳法索",
    "cambodia": "柬埔寨",
    "柬埔寨": "柬埔寨",
    "laos": "老挝",
    "老挝": "老挝",
    "cyprus": "塞浦路斯",
    "塞浦路斯": "塞浦路斯",
    "isle of man": "马恩岛",
    "马恩岛": "马恩岛",
    "norfolk island": "诺福克岛",
    "诺福克岛": "诺福克岛",
    "uruguay": "乌拉圭",
    "乌拉圭": "乌拉圭",
    "belarus": "白俄罗斯",
    "白俄罗斯": "白俄罗斯",
    "tunisia": "突尼斯",
    "突尼斯": "突尼斯",
    "kuwait": "科威特",
    "科威特": "科威特",
    "puerto rico": "波多黎各",
    "波多黎各": "波多黎各",
    "sudan": "苏丹",
    "苏丹": "苏丹",
    "algeria": "阿尔及利亚",
    "阿尔及利亚": "阿尔及利亚",
    "nigeria": "尼日利亚",
    "尼日利亚": "尼日利亚",
    "luxembourg": "卢森堡",
    "卢森堡": "卢森堡",
    "sri lanka": "斯里兰卡",
    "斯里兰卡": "斯里兰卡",
    "british virgin islands": "英属维尔京群岛",
    "英属维尔京群岛": "英属维尔京群岛",
    "ghana": "加纳",
    "加纳": "加纳",
    "ecuador": "厄瓜多尔",
    "厄瓜多尔": "厄瓜多尔",
    "oman": "阿曼",
    "阿曼": "阿曼",
    "niger": "尼日尔",
    "尼日尔": "尼日尔",
    "st. kitts & nevis": "圣基茨和尼维斯",
    "saint kitts and nevis": "圣基茨和尼维斯",
    "圣基茨和尼维斯": "圣基茨和尼维斯",
    "uzbekistan": "乌兹别克斯坦",
    "乌兹别克斯坦": "乌兹别克斯坦",
    "kyrgyzstan": "吉尔吉斯斯坦",
    "吉尔吉斯斯坦": "吉尔吉斯斯坦",
    "french guiana": "法属圭亚那",
    "法属圭亚那": "法属圭亚那",
    "iceland": "冰岛",
    "冰岛": "冰岛",
    "réunion": "留尼汪",
    "reunion": "留尼汪",
    "留尼汪": "留尼汪",
    "malta": "马耳他",
    "马耳他": "马耳他",
}

GREATER_CHINA_COUNTRIES: Final[set[str]] = {
    "中国",
    "中国香港特别行政区",
    "中国台湾省",
    "中国澳门特别行政区",
}

CHINA_REGION_MAP: Final[dict[str, str]] = {
    "beijing": "北京市",
    "北京市": "北京市",
    "shanghai": "上海市",
    "上海市": "上海市",
    "tianjin": "天津市",
    "天津市": "天津市",
    "chongqing": "重庆市",
    "重庆": "重庆市",
    "重庆市": "重庆市",
    "guangdong": "广东省",
    "广东": "广东省",
    "广东省": "广东省",
    "zhejiang": "浙江省",
    "浙江": "浙江省",
    "浙江省": "浙江省",
    "sichuan": "四川省",
    "四川": "四川省",
    "四川省": "四川省",
    "jiangsu": "江苏省",
    "江苏": "江苏省",
    "江苏省": "江苏省",
    "shandong": "山东省",
    "山东": "山东省",
    "山东省": "山东省",
    "fujian": "福建省",
    "福建": "福建省",
    "福建省": "福建省",
    "hubei": "湖北省",
    "湖北": "湖北省",
    "湖北省": "湖北省",
    "guizhou": "贵州省",
    "贵州": "贵州省",
    "贵州省": "贵州省",
    "henan": "河南省",
    "河南": "河南省",
    "河南省": "河南省",
    "gansu": "甘肃省",
    "甘肃": "甘肃省",
    "甘肃省": "甘肃省",
    "hebei": "河北省",
    "河北": "河北省",
    "河北省": "河北省",
    "hunan": "湖南省",
    "湖南": "湖南省",
    "湖南省": "湖南省",
    "anhui": "安徽省",
    "安徽": "安徽省",
    "安徽省": "安徽省",
    "liaoning": "辽宁省",
    "辽宁": "辽宁省",
    "辽宁省": "辽宁省",
    "shanxi": "山西省",
    "山西": "山西省",
    "山西省": "山西省",
    "shaanxi": "陕西省",
    "陕西": "陕西省",
    "陕西省": "陕西省",
    "jiangxi": "江西省",
    "江西": "江西省",
    "江西省": "江西省",
    "guangxi": "广西壮族自治区",
    "guangxi zhuangzu": "广西壮族自治区",
    "广西": "广西壮族自治区",
    "广西壮族自治区": "广西壮族自治区",
    "heilongjiang": "黑龙江省",
    "黑龙江": "黑龙江省",
    "黑龙江省": "黑龙江省",
    "jilin": "吉林省",
    "吉林": "吉林省",
    "吉林省": "吉林省",
    "yunnan": "云南省",
    "云南": "云南省",
    "云南省": "云南省",
    "xinjiang": "新疆维吾尔自治区",
    "xinjiang uygur": "新疆维吾尔自治区",
    "新疆": "新疆维吾尔自治区",
    "新疆维吾尔自治区": "新疆维吾尔自治区",
    "hainan": "海南省",
    "海南": "海南省",
    "海南省": "海南省",
    "inner mongolia": "内蒙古自治区",
    "nei mongol": "内蒙古自治区",
    "neimenggu": "内蒙古自治区",
    "内蒙古": "内蒙古自治区",
    "内蒙古自治区": "内蒙古自治区",
    "ningxia": "宁夏回族自治区",
    "ningxia huizu": "宁夏回族自治区",
    "宁夏": "宁夏回族自治区",
    "宁夏回族自治区": "宁夏回族自治区",
    "qinghai": "青海省",
    "青海": "青海省",
    "青海省": "青海省",
    "xizang": "西藏自治区",
    "tibet": "西藏自治区",
    "西藏": "西藏自治区",
    "西藏自治区": "西藏自治区",
    "hong kong": "香港特别行政区",
    "hk": "香港特别行政区",
    "香港": "香港特别行政区",
    "香港特别行政区": "香港特别行政区",
    "taiwan": "台湾省",
    "tw": "台湾省",
    "台湾": "台湾省",
    "台湾省": "台湾省",
    "macao": "澳门特别行政区",
    "macau": "澳门特别行政区",
    "澳门": "澳门特别行政区",
    "澳门特别行政区": "澳门特别行政区",
}

CHINA_CITY_MAP: Final[dict[str, str]] = {
    "beijing": "北京",
    "shanghai": "上海",
    "guangzhou": "广州",
    "hangzhou": "杭州",
    "chengdu": "成都",
    "shenzhen": "深圳",
    "nanjing": "南京",
    "yangzhou": "扬州",
    "lanzhou": "兰州",
    "huizhou": "惠州",
    "qingdao": "青岛",
    "chongqing": "重庆",
    "guiyang": "贵阳",
    "wuhan": "武汉",
    "jinan": "济南",
    "zhengzhou": "郑州",
    "ningbo": "宁波",
    "shiyan": "十堰",
    "xiamen": "厦门",
    "suzhou": "苏州",
    "tianjin": "天津",
    "hefei": "合肥",
    "kunming": "昆明",
    "changchun": "长春",
    "harbin": "哈尔滨",
    "xian": "西安",
    "xi'an": "西安",
    "changsha": "长沙",
    "wuxi": "无锡",
    "yantai": "烟台",
    "fuzhou": "福州",
    "taiyuan": "太原",
    "shijiazhuang": "石家庄",
    "nanning": "南宁",
    "urumqi": "乌鲁木齐",
    "nanchang": "南昌",
    "foshan": "佛山",
    "dongguan": "东莞",
    "zhuhai": "珠海",
    "zhongshan": "中山",
    "quanzhou": "泉州",
    "wenzhou": "温州",
    "jiaxing": "嘉兴",
    "shaoxing": "绍兴",
    "jinhua": "金华",
    "taizhou": "台州",
    "nantong": "南通",
    "changzhou": "常州",
    "xuzhou": "徐州",
    "yancheng": "盐城",
    "zhenjiang": "镇江",
    "lianyungang": "连云港",
    "weifang": "潍坊",
    "linyi": "临沂",
    "dezhou": "德州",
    "jining": "济宁",
    "luoyang": "洛阳",
    "zhumadian": "驻马店",
    "anyang": "安阳",
    "luohe": "漯河",
    "xiangyang": "襄阳",
    "yichang": "宜昌",
    "jingzhou": "荆州",
    "huangshi": "黄石",
    "leshan": "乐山",
    "shenyang": "沈阳",
    "guyuan": "固原",
    "hohhot": "呼和浩特",
    "fuqing": "福清",
    "zhongwei": "中卫",
    "suqian": "宿迁",
    "zhangzhou": "漳州",
    "dalian": "大连",
    "xinyang": "信阳",
    "jiangmen": "江门",
    "shaoyang": "邵阳",
    "fuyang": "阜阳",
    "langfang": "廊坊",
    "huzhou": "湖州",
    "weihai": "威海",
    "ningde": "宁德",
    "xuchang": "许昌",
    "wuhu": "芜湖",
    "jilin": "吉林",
    "haikou": "海口",
    "turpan": "吐鲁番",
    "huaihua": "怀化",
    "zhangjiakou": "张家口",
    "putian": "莆田",
    "panjin": "盘锦",
    "ma'anshan": "马鞍山",
    "jingdezhen": "景德镇",
    "ganzhou": "赣州",
    "chizhou": "池州",
    "yiwu": "义乌",
    "tangshan": "唐山",
    "shihezi": "石河子",
    "shantou": "汕头",
    "qingyuan": "清远",
    "mianyang": "绵阳",
    "lu'an": "六安",
    "jiujiang": "九江",
    "hulunbuir": "呼伦贝尔",
    "chuzhou": "滁州",
    "changji": "昌吉",
    "benxi": "本溪",
    "baoding": "保定",
    "zhuzhou": "株洲",
    "yinchuan": "银川",
    "xingtai": "邢台",
    "xiangtan": "湘潭",
    "ulanqab": "乌兰察布",
    "tai'an": "泰安",
    "shangqiu": "商丘",
    "qinhuangdao": "秦皇岛",
    "puyang": "濮阳",
    "pu'er": "普洱",
    "pingdingshan": "平顶山",
    "meishan": "眉山",
    "maoming": "茂名",
    "loudi": "娄底",
    "jishou": "吉首",
    "huanggang": "黄冈",
    "dingxi": "定西",
    "dali": "大理",
    "ziyang": "资阳",
    "zibo": "淄博",
    "zaozhuang": "枣庄",
    "yuxi": "玉溪",
    "yuncheng": "运城",
    "yingkou": "营口",
    "yanji": "延吉",
    "xinzhou": "忻州",
    "xinxiang": "新乡",
    "xianyang": "咸阳",
    "xiantao": "仙桃",
    "tianshui": "天水",
    "suining": "遂宁",
    "siping": "四平",
    "sheung pak nai": "上白泥",
    "shanwei": "汕尾",
    "quzhou": "衢州",
    "qingyang": "庆阳",
    "nanyang": "南阳",
    "nanping": "南平",
    "meizhou": "梅州",
    "longnan": "陇南",
    "liaocheng": "聊城",
    "jingmen": "荆门",
    "huainan": "淮南",
    "heyuan": "河源",
    "hengyang": "衡阳",
    "hebi": "鹤壁",
    "fushun": "抚顺",
    "deyang": "德阳",
    "chifeng": "赤峰",
    "chaozhou": "潮州",
    "cangzhou": "沧州",
    "binzhou": "滨州",
    "zunyi": "遵义",
    "zhoukou": "周口",
    "zhaoqing": "肇庆",
    "yuyao": "余姚",
    "yunfu": "云浮",
    "yulin": "玉林",
    "yueyang": "岳阳",
    "yibin": "宜宾",
    "yangquan": "阳泉",
    "yangjiang": "阳江",
    "ya'an": "雅安",
    "xichang": "西昌",
    "xianning": "咸宁",
    "wuzhou": "梧州",
    "wuwei": "武威",
    "shaoguan": "韶关",
    "sanming": "三明",
    "sanmenxia": "三门峡",
    "nanchong": "南充",
    "mudanjiang": "牡丹江",
    "luzhou": "泸州",
    "longyan": "龙岩",
    "lishui": "丽水",
    "kuytun": "奎屯",
    "jiyuan": "济源",
    "jiaozuo": "焦作",
    "ji'an": "吉安",
    "huludao": "葫芦岛",
    "heze": "菏泽",
    "hengshui": "衡水",
    "hechi": "河池",
    "hanzhong": "汉中",
    "handan": "邯郸",
    "fu'an": "福安",
    "dongying": "东营",
    "dongfang": "东方",
    "daqing": "大庆",
    "chenzhou": "郴州",
    "changde": "常德",
    "bozhou": "亳州",
    "bengbu": "蚌埠",
    "baotou": "包头",
    "baoji": "宝鸡",
    "baiyin": "白银",
    "baise": "百色",
    "anshan": "鞍山",
    "aksu": "阿克苏",
    "hong kong": "香港",
    "taipei": "台北",
    "new taipei": "新北",
    "kaohsiung": "高雄",
    "taichung": "台中",
    "tainan": "台南",
    "macau": "澳门",
}

CITY_CASE_EXCEPTIONS: Final[dict[str, str]] = {
    "xi'an": "Xi'an",
    "pu'er": "Pu'er",
    "ma'anshan": "Ma'anshan",
    "lu'an": "Lu'an",
    "ji'an": "Ji'an",
    "tai'an": "Tai'an",
    "ya'an": "Ya'an",
    "sheung pak nai": "Sheung Pak Nai",
    "hong kong": "Hong Kong",
    "new taipei": "New Taipei",
}


def normalize_country_name(value: str) -> str:
    text = (value or "").strip()
    if not text:
        return ""
    normalized = COUNTRY_NAME_MAP.get(text.lower())
    if normalized:
        return normalized
    return text


def is_greater_china_country(value: str) -> bool:
    return normalize_country_name(value) in GREATER_CHINA_COUNTRIES


def normalize_region_name(country: str, region: str) -> str:
    text = (region or "").strip()
    if not text:
        return ""
    if is_greater_china_country(country):
        return CHINA_REGION_MAP.get(text.lower(), text)
    return text


def to_preferred_english_city_name(value: str) -> str:
    key = value.strip().lower()
    if not key:
        return ""
    if key in CITY_CASE_EXCEPTIONS:
        return CITY_CASE_EXCEPTIONS[key]
    return " ".join(part.capitalize() for part in key.split())


def normalize_city_name(country: str, region: str, city: str) -> str:
    text = (city or "").strip()
    if not text:
        return ""
    if is_greater_china_country(country):
        reverse_map = {zh_name: en_name for en_name, zh_name in CHINA_CITY_MAP.items()}
        english_key = reverse_map.get(text)
        if english_key:
            return to_preferred_english_city_name(english_key)
        if text.lower() in CHINA_CITY_MAP:
            return to_preferred_english_city_name(text)
    return text


def normalize_location_fields(country: str, region: str, city: str) -> tuple[str, str, str]:
    normalized_country = normalize_country_name(country)
    normalized_region = normalize_region_name(normalized_country, region)
    normalized_city = normalize_city_name(normalized_country, normalized_region, city)
    if normalized_region == "香港特别行政区":
        normalized_country = "中国香港特别行政区"
    elif normalized_region == "澳门特别行政区":
        normalized_country = "中国澳门特别行政区"
    elif normalized_region == "台湾省":
        normalized_country = "中国台湾省"
    elif normalized_country in {"中国香港特别行政区", "中国澳门特别行政区", "中国台湾省"}:
        if (
            normalized_region.endswith("省")
            or normalized_region.endswith("市")
            or normalized_region.endswith("自治区")
        ):
            normalized_country = "中国"
    return normalized_country, normalized_region, normalized_city
